"""add send manager contact bool field

Revision ID: 0f4b58dc0921
Revises: a31948984127
Create Date: 2025-11-25 14:49:12.256989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f4b58dc0921'
down_revision: Union[str, Sequence[str], None] = 'a31948984127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatwoot_conversation', sa.Column('manager_contact_sent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatwoot_conversation', 'manager_contact_sent')
    # ### end Alembic commands ###
