"""добавил поле для хранения стадии сделки

Revision ID: 30dbdffb6894
Revises: 7f915f7e7e11
Create Date: 2025-09-11 15:44:54.505204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30dbdffb6894'
down_revision: Union[str, Sequence[str], None] = '7f915f7e7e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bx_deal', sa.Column('stage_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bx_deal', 'stage_id')
    # ### end Alembic commands ###
