"""add last trancribation date

Revision ID: 31723cc71086
Revises: 471dd7d2f043
Create Date: 2025-08-20 15:29:48.471223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31723cc71086'
down_revision: Union[str, Sequence[str], None] = '471dd7d2f043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bx_deal', sa.Column('last_transcribed_call', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bx_deal', 'last_transcribed_call')
    # ### end Alembic commands ###
