"""init

Revision ID: 471dd7d2f043
Revises: 
Create Date: 2025-08-19 17:45:22.583196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '471dd7d2f043'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bx_deal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bx_id', sa.Integer(), nullable=False),
    sa.Column('bx_portal', sa.String(length=255), nullable=False),
    sa.Column('bx_funnel_id', sa.String(length=55), nullable=False),
    sa.Column('bx_contact_id', sa.Integer(), nullable=True),
    sa.Column('chatwoot_contact_id', sa.Integer(), nullable=True),
    sa.Column('chatwoot_conversation_id', sa.Integer(), nullable=True),
    sa.Column('last_sync_chatwoot', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bx_id', 'bx_portal', name='uq_bx_deals_bx_id_portal')
    )
    op.create_table('chatwoot_conversation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chatwoot_id', sa.Integer(), nullable=False),
    sa.Column('last_message_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chatwoot_id', name='uq_cw_chatwoot_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatwoot_conversation')
    op.drop_table('bx_deal')
    # ### end Alembic commands ###
