"""добавил поле для сохранение выбранного пользователем диалога в модель BxDealCwLink

Revision ID: 5c574393ff97
Revises: 978aa4b00377
Create Date: 2025-10-23 16:13:05.405665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c574393ff97'
down_revision: Union[str, Sequence[str], None] = '978aa4b00377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bx_deal_cw_link', sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index('uq_link_primary_per_deal', 'bx_deal_cw_link', ['bx_portal', 'bx_deal_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_link_primary_per_deal', table_name='bx_deal_cw_link', postgresql_where=sa.text('is_primary = true'))
    op.drop_column('bx_deal_cw_link', 'is_primary')
    # ### end Alembic commands ###
