"""add proccess events 2

Revision ID: 6e354efae1f7
Revises: e510bdb8632d
Create Date: 2025-08-22 12:57:24.650341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e354efae1f7'
down_revision: Union[str, Sequence[str], None] = 'e510bdb8632d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bx_handler_process',
    sa.Column('event_code', sa.String(length=255), nullable=False),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('event_code')
    )
    op.create_index(op.f('ix_bx_handler_process_event_code'), 'bx_handler_process', ['event_code'], unique=True)
    op.drop_table('processed_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('event_uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('event_uid', name=op.f('processed_events_pkey'))
    )
    op.drop_index(op.f('ix_bx_handler_process_event_code'), table_name='bx_handler_process')
    op.drop_table('bx_handler_process')
    # ### end Alembic commands ###
