"""добавил модель для хранения информации о транскрибированых звонках

Revision ID: 7f915f7e7e11
Revises: 6e354efae1f7
Create Date: 2025-09-10 15:02:08.252765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f915f7e7e11'
down_revision: Union[str, Sequence[str], None] = '6e354efae1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bx_processed_call',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portal', sa.String(length=255), nullable=False),
    sa.Column('deal_bx_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(length=128), nullable=False),
    sa.Column('transcribation', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_to_bx', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portal', 'call_id', name='uq_portal_call')
    )
    op.add_column('bx_deal', sa.Column('last_sync_comment_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bx_deal', 'last_sync_comment_id')
    op.drop_table('bx_processed_call')
    # ### end Alembic commands ###
