"""fix add TranscriptionJob

Revision ID: 978aa4b00377
Revises: f177e38de413
Create Date: 2025-10-23 12:28:45.576749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '978aa4b00377'
down_revision: Union[str, Sequence[str], None] = 'f177e38de413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bx_contact_cw_map',
    sa.Column('bx_portal', sa.String(length=255), nullable=False),
    sa.Column('bx_contact_id', sa.Integer(), nullable=False),
    sa.Column('cw_contact_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('bx_portal', 'bx_contact_id')
    )
    op.create_table('bx_deal_cw_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bx_portal', sa.String(length=255), nullable=False),
    sa.Column('bx_deal_id', sa.Integer(), nullable=False),
    sa.Column('cw_conversation_id', sa.Integer(), nullable=False),
    sa.Column('cw_inbox_id', sa.Integer(), nullable=False),
    sa.Column('cw_contact_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bx_portal', 'bx_deal_id', 'cw_conversation_id', name='uq_link_portal_deal_conv')
    )
    op.create_index('ix_link_bx_deal', 'bx_deal_cw_link', ['bx_portal', 'bx_deal_id'], unique=False)
    op.create_index('ix_link_cw_conversation_id', 'bx_deal_cw_link', ['cw_conversation_id'], unique=False)
    op.create_table('transcription_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portal', sa.String(length=255), nullable=False),
    sa.Column('deal_bx_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcription_job_deal_bx_id'), 'transcription_job', ['deal_bx_id'], unique=False)
    op.create_index(op.f('ix_transcription_job_portal'), 'transcription_job', ['portal'], unique=False)
    op.create_index('uq_transcription_job_active', 'transcription_job', ['portal', 'deal_bx_id'], unique=True, postgresql_where=sa.text("status IN ('new', 'running', 'retry')"))
    op.drop_column('bx_deal', 'chatwoot_conversation_id')
    op.drop_column('bx_deal', 'chatwoot_contact_id')
    op.create_unique_constraint(None, 'transport_activation', ['inbox_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transport_activation', type_='unique')
    op.add_column('bx_deal', sa.Column('chatwoot_contact_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bx_deal', sa.Column('chatwoot_conversation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index('uq_transcription_job_active', table_name='transcription_job', postgresql_where=sa.text("status IN ('new', 'running', 'retry')"))
    op.drop_index(op.f('ix_transcription_job_portal'), table_name='transcription_job')
    op.drop_index(op.f('ix_transcription_job_deal_bx_id'), table_name='transcription_job')
    op.drop_table('transcription_job')
    op.drop_index('ix_link_cw_conversation_id', table_name='bx_deal_cw_link')
    op.drop_index('ix_link_bx_deal', table_name='bx_deal_cw_link')
    op.drop_table('bx_deal_cw_link')
    op.drop_table('bx_contact_cw_map')
    # ### end Alembic commands ###
