"""add last message date field

Revision ID: a31948984127
Revises: f87d68717817
Create Date: 2025-11-19 11:47:19.817824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a31948984127'
down_revision: Union[str, Sequence[str], None] = 'f87d68717817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatwoot_conversation', sa.Column('last_client_message_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chatwoot_conversation', sa.Column('next_meeting_datetime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chatwoot_conversation', sa.Column('warmup_number', sa.Integer(), nullable=True))
    op.add_column('chatwoot_conversation', sa.Column('last_warmup_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatwoot_conversation', 'last_warmup_date')
    op.drop_column('chatwoot_conversation', 'warmup_number')
    op.drop_column('chatwoot_conversation', 'next_meeting_datetime')
    op.drop_column('chatwoot_conversation', 'last_client_message_date')
    # ### end Alembic commands ###
