"""fix import BaseModel

Revision ID: f177e38de413
Revises: 2b2c259f5928
Create Date: 2025-10-16 16:48:37.902610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f177e38de413'
down_revision: Union[str, Sequence[str], None] = '2b2c259f5928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_routing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('agent_code', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('inbox_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone', 'agent_code', 'kind', name='uq_contact_agent_kind')
    )
    op.create_index(op.f('ix_contact_routing_agent_code'), 'contact_routing', ['agent_code'], unique=False)
    op.create_index(op.f('ix_contact_routing_phone'), 'contact_routing', ['phone'], unique=False)
    op.create_table('rr_cursor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_code_and_kind', sa.String(length=64), nullable=False),
    sa.Column('last_index', sa.Integer(), server_default=sa.text('-1'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_code_and_kind')
    )
    op.create_table('transport_activation',
    sa.Column('inbox_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('inbox_id'),
    sa.UniqueConstraint('inbox_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transport_activation')
    op.drop_table('rr_cursor')
    op.drop_index(op.f('ix_contact_routing_phone'), table_name='contact_routing')
    op.drop_index(op.f('ix_contact_routing_agent_code'), table_name='contact_routing')
    op.drop_table('contact_routing')
    # ### end Alembic commands ###
