"""delete active field in ContactRouting

Revision ID: f17ed24b5e86
Revises: f3ad573e94b4
Create Date: 2025-10-15 16:10:46.776882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f17ed24b5e86'
down_revision: Union[str, Sequence[str], None] = 'f3ad573e94b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
