"""add field for check send agent contact

Revision ID: f87d68717817
Revises: 5c574393ff97
Create Date: 2025-11-17 10:47:31.302278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f87d68717817'
down_revision: Union[str, Sequence[str], None] = '5c574393ff97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatwoot_conversation', sa.Column('agent_contact_sent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatwoot_conversation', 'agent_contact_sent')
    # ### end Alembic commands ###
